### ISSUE TITLE
3*3卷积核是否不能偏移

### ISSUE THREAD

**Issue by Claraeunice** [YaoleiQi/DSCNet#17]
在您的工作中，我尝试调用DSConv时参数使用3*3卷积核，但是我发现它并没有执行可变形卷积的代码（if if_offset内的内容）

**Comment by YaoleiQi** [comment]
当if_offset为false 执行的是标准的1*n或者n*1的卷积，如果为true则会发生形变~

**Comment by Claraeunice** [comment]
> 当if_offset为false 执行的是标准的1_n或者n_1的卷积，如果为true则会发生形变~

选择为true，但是如果想替换3*3卷积，它不会执行代码里的那个for循环，因为center=self.numbers-1

**Comment by Claraeunice** [comment]
> 当if_offset为false 执行的是标准的1_n或者n_1的卷积，如果为true则会发生形变~

选择为true，但是如果想替换3*3卷积，它不会执行代码里的那个for循环，因为center=self.numpoints-1

**Comment by Claraeunice** [comment]
> 当if_offset为false 执行的是标准的1_n或者n_1的卷积，如果为true则会发生形变~

在调用DSConv时，kernerl_size为3时， 代码中的
`for index in range(1, center):
                    y_offset_new[center + index] = (y_offset_new[center + index - 1] + y_offset[center + index])
                    y_offset_new[center - index] = (y_offset_new[center - index + 1] + y_offset[center - index])`
并不会执行，因为center=self.num_points-1
那么遇到这个情况怎么办呢？

**Comment by Claraeunice** [comment]
> 当if_offset为false 执行的是标准的1_n或者n_1的卷积，如果为true则会发生形变~

也就是说，这样看起来，3*3卷积不能偏移，但是改成7*7时，会报错

**Comment by Claraeunice** [comment]
> 当if_offset为false 执行的是标准的1_n或者n_1的卷积，如果为true则会发生形变~

这对我来说非常着急，恳请作者早些回复，谢谢！！

**Comment by YaoleiQi** [comment]
您好，非常感谢您的问题，但是我不太理解什么叫做替换3*3的卷积呢？可能需要深入交流一下，如果方便是否可以加一下联系方式？可以加我的Wechat：13082556710，感谢

**Comment by Claraeunice** [comment]
> 您好，非常感谢您的问题，但是我不太理解什么叫做替换3*3的卷积呢？可能需要深入交流一下，如果方便是否可以加一下联系方式？可以加我的Wechat：13082556710，感谢

好的！！！真的感谢

**Comment by Beck-127** [comment]
作者您好，我最近在复现代码的时候也遇到了这个问题。在_S3_DSConv_中，定义的num_points=kernel_size=3, center = int(self.num_points // 2)=1,那么for index in range(1, center):这个循环似乎是不运行的，请问这个该如何理解呢？
