### ISSUE TITLE
蛇形卷积适用情景

### ISSUE THREAD

**Issue by Remosy** [YaoleiQi/DSCNet#42]
请问一下，这样的卷积核是不是更适用在线状图的特征上？比如血管，裂纹，道路等。对于其它不是由线状特征决定的情况，比如人脸，物品分类什么的，它可能会有更多误检的可能？

**Comment by YaoleiQi** [comment]
您好，很感谢您的关注，因为近期工作变化，没能及时回复，希望您能理解。这个问题非常有趣，我们最初的目的是为了针对这样的线状图设计的，做了不少的工作，发现有一定的提升效果，当然在近期的尝试中，我们也发现这一个算子对一些非线性结构，似乎有时也能带来一些提升效果，近期cite我们工作的一些目标检测的论文中也展示了其与yolo适配后，对一些非线性结构的检测性能提升，这也是我们欣喜的，当然这份工作仍有很多的不足和可以后续继续推进的部分，可能需要大家一起的探索！谢谢！
