### ISSUE TITLE
About Visualization Issues

### ISSUE THREAD

**Issue by XiandongWang** [YaoleiQi/DSCNet#7]
DSCNet is a very impressive work, and I'm very interested in the visualization of fig8 in the supplementary materials of the paper. Could you please share the visualization code if possible?

**Comment by YaoleiQi** [comment]
Thank you for your attention. The implementation of this code is straightforward. It essentially takes the coordinates of the convolution kernel at the corresponding position in each layer of the network and superimposes them on the original image.

We are currently planning to collect and organize a library of generic open-source algorithms for working with tubular structures. This code you mentioned will be included in the appropriate libraries, so it may not be uploaded to this file, but it will also be available on my GitHub later.

**Comment by LualuOntheSea** [comment]
Have you solved this problem?  If it's resolved, could you share the code?  Thanks! @XiandongWang
